on: [push, pull_request]
name: ghostdb-sdk-golang-test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: install_go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: checkout_code
        uses: actions/checkout@v2
      - name: run_tests
        run: go test ./... -v